name: book_store
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  google_fonts: ^3.0.1
  rive_splash_screen: ^0.1.1
  flutter_svg: ^1.1.4
  rate_in_stars: ^0.0.3
  water_drop_nav_bar: ^2.2.0+4
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  ionicons: ^0.2.1
  panara_dialogs: ^0.1.2
  animated_splash_screen: ^1.3.0
  get_storage: ^2.0.3
  get: ^4.6.5
  equatable: ^2.0.5
  flutter_typeahead: ^4.1.1






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
